name: learn_dart_frog
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dart_frog: ^0.1.0
  equatable: ^2.0.5
  json_annotation: ^4.7.0
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.3.0
  json_serializable: ^6.5.1
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
